### ISSUE TITLE
change the .container background-color

### ISSUE THREAD

**Issue by emjayess** [geekmeetfm/geek_meteor_todos#1]
### todo:

in `geek_meteor_todos.css`, change the `.container` class' background-color from 'white' to 'turquoise'...
### want:

``` css
.container {
  max-width: 600px;
  margin: 0 auto;
  min-height: 100%;
  background-color: turquoise;
}
```
